<a href="https://colab.research.google.com/github/Roy225/Deep_learning/blob/main/practise_myself.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
from word2number import w2n

In [ ]:
df = pd.read_csv('train.csv')
df

    Mileage  Age(yrs)  Sell Price($)
0     69000         6          18000
1     35000         3          34000
2     57000         5          26100
3     22500         2          40000
4     46000         4          31500
5     59000         5          26750
6     52000         5          32000
7     72000         6          19300
8     91000         8          12000
9     67000         6          22000
10    83000         7          18700
11    79000         7          19500
12    59000         5          26000
13    58780         4          27500
14    82450         7          19400
15    25400         3          35000
16    28000         2          35500
17    69000         5          19700
18    87600         8          12800
19    52000         5          28200

In [ ]:
X = df.drop(['Sell Price($)'], axis='columns')
X

    Mileage  Age(yrs)
0     69000         6
1     35000         3
2     57000         5
3     22500         2
4     46000         4
5     59000         5
6     52000         5
7     72000         6
8     91000         8
9     67000         6
10    83000         7
11    79000         7
12    59000         5
13    58780         4
14    82450         7
15    25400         3
16    28000         2
17    69000         5
18    87600         8
19    52000         5

In [ ]:
y = df['Sell Price($)']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     26750
6     32000
7     19300
8     12000
9     22000
10    18700
11    19500
12    26000
13    27500
14    19400
15    35000
16    35500
17    19700
18    12800
19    28200
Name: Sell Price($), dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [ ]:
reg.predict(X_test)

array([14027.77584146, 22936.485333  , 17178.69254281, 38509.69232767])

In [ ]:
reg.score(X_train,y_train)

0.9149100104613432

In [ ]:
y_test

8     12000
17    19700
10    18700
3     40000
Name: Sell Price($), dtype: int64